//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace org { namespace alljoyn { namespace Icon {

ref class IconConsumer;

public ref class IconGetContentResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Windows::Foundation::Collections::IVector<byte>^ Content
    {
        Windows::Foundation::Collections::IVector<byte>^ get() { return m_interfaceMemberContent; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IVector<byte>^ value) { m_interfaceMemberContent = value; }
    }
    
    static IconGetContentResult^ CreateSuccessResult(_In_ Windows::Foundation::Collections::IVector<byte>^ interfaceMemberContent)
    {
        auto result = ref new IconGetContentResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Content = interfaceMemberContent;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static IconGetContentResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new IconGetContentResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Windows::Foundation::Collections::IVector<byte>^ m_interfaceMemberContent;
};

public ref class IconGetUrlResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ Url
    {
        Platform::String^ get() { return m_interfaceMemberUrl; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberUrl = value; }
    }
    
    static IconGetUrlResult^ CreateSuccessResult(_In_ Platform::String^ interfaceMemberUrl)
    {
        auto result = ref new IconGetUrlResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Url = interfaceMemberUrl;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static IconGetUrlResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new IconGetUrlResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Platform::String^ m_interfaceMemberUrl;
};

public ref class IconJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property IconConsumer^ Consumer
    {
        IconConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ IconConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    IconConsumer^ m_consumer;
};

public ref class IconGetMimeTypeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ MimeType
    {
        Platform::String^ get() { return m_value; }
    internal:
        void set(_In_ Platform::String^ value) { m_value = value; }
    }

    static IconGetMimeTypeResult^ CreateSuccessResult(_In_ Platform::String^ value)
    {
        auto result = ref new IconGetMimeTypeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MimeType = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static IconGetMimeTypeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new IconGetMimeTypeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Platform::String^ m_value;
};

public ref class IconGetSizeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Size
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static IconGetSizeResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new IconGetSizeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Size = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static IconGetSizeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new IconGetSizeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class IconGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static IconGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new IconGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static IconGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new IconGetVersionResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint16 m_value;
};

} } } 
