//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace Introspectable {

public interface class IIntrospectableService
{
public:
    // Implement this function to handle calls to the GetDescriptionLanguages method.
    Windows::Foundation::IAsyncOperation<IntrospectableGetDescriptionLanguagesResult^>^ GetDescriptionLanguagesAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the IntrospectWithDescription method.
    Windows::Foundation::IAsyncOperation<IntrospectableIntrospectWithDescriptionResult^>^ IntrospectWithDescriptionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberLanguageTag);

};

} } } 
